<a href="https://colab.research.google.com/github/kailunjin/Data-Analysis-and-Topic-Modeling-of-Hymns/blob/main/CS_376_translator_evaluation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Evaluating Translation Quality Using Small Open-Source LLMs（EN-CH）

# **Goal**

We study how well small open-source large language models (LLMs) can evaluate translation quality. Using an English-to-Chinese dataset with human evaluation scores, we compare model-generated scores (based on faithfulness and fluency) with human judgments to measure alignment and consistency.

## What Success Looks Like?
LLM scores show measurable correlation with human scores

Differences between models are observable

Clear failure cases can be identified and explained

## Course Objectives
TM-TransformerDataFlow:

We demonstrate understanding of transformer-based LLMs by analyzing how input text (source + translation) is processed into evaluation outputs (scores and reasoning).

OG-LLM-Prompting:

We design structured prompts to guide LLMs to produce consistent evaluation scores and short explanations, and analyze how prompt design affects output quality.

OG-LLM-ContextAndTools:

We build a pipeline using pretrained LLMs that takes translation pairs as input and outputs structured evaluation results.

OG-LLM-Eval:

We evaluate model performance by comparing LLM scores with human scores using correlation and error metrics.

Overall-LLM-Failures:

We analyze cases where LLM evaluations differ from human judgments to identify limitations such as format errors and shallow reasoning.

# Model Selection:
We select three small open-source models to balance performance and efficiency:

[Qwen: Qwen2.5-3B-Instruct](https://huggingface.co/Qwen/Qwen2.5-3B-Instruct)

This model is relatively strong in both Chinese and English capabilities and is particularly suitable for translation tasks. We take it as a representative model with strong performance to observe whether the model can approach human scoring at a medium scale.

[microsoft: Phi-3.5-mini-instruct](https://huggingface.co/microsoft/Phi-3.5-mini-instruct)

This model has smaller parameters, but its reasoning ability is well optimized. It was chosen to test whether small models can also make reasonable evaluations and the balance between performance and efficiency.

[HuggingFaceTB: SmolLM2-1.7B-Instruct](https://huggingface.co/HuggingFaceTB/SmolLM2-1.7B-Instruct)

This is a very lightweight model with the lowest computational cost. We use it as the lower limit baseline to see how far the model can still perform with very few resources.

# 1.Setup

In [ ]:
!pip install transformers accelerate

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.13.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.29.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.11.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (2.10.0+cu128)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.24.2)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=2.0.0->accelerate) (1.5.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (3.13)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.1.2)

In [ ]:
import pandas as pd

# 2. Dataset

We use the English–Chinese (En–Zh) subset of the WMT20 MLQE dataset from Hugging Face.
This dataset contains English sentences and their Chinese translations generated by neural machine translation (NMT) systems, along with human evaluation scores.

The human scores are obtained using Direct Assessment (DA), where multiple professional annotators rate translation quality. These scores are then normalized into z-scores, which serve as our ground-truth reference.

To make experimentation efficient, we sample a subset of the test split:

In [ ]:
from datasets import load_dataset

ds = load_dataset("wmt/wmt20_mlqe_task1", "en-zh")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [ ]:
data = ds["test"].select(range(100))

sample_100 = pd.DataFrame({
    "source_en": [item["translation"]["en"] for item in data],
    "translation_zh": [item["translation"]["zh"] for item in data],
    "human_score": [item["mean"] for item in data]
})

sample_100.head()

,source_en,translation_zh,human_score
0,"Milhaud also used jazz idioms, as in his Suite...","米勒豪德也使用爵士乐成语, 就像他的套房里使用单管、小提琴和钢琴一样.",24.333334
1,He then wrongfooted May by parking just behind...,"然后他把梅的车停在 LDV 后面以阻止它的卸货, 弄错了.",68.500000
2,"It inhabits the Atlantic, Indian, and Pacific ...",它居住在大西洋、印度洋、太平洋和地中海。,76.333336
3,The Final 8 began with a victory against Benet...,在 2009 年 4 月 2 日的四分之一决赛中 ， 最后 8 场比赛首先战胜了贝内顿 · ...,56.333332
4,The verandahs on the west and south elevations...,西面和南面的斜坡上有一排多孔的多孔柱子.,54.666668

Each example in our dataset contains:



*   the original English sentence
*   the Chinese translation
*   a human evaluation score

# Strengths
* Provides human judgments, enabling direct comparison with LLM evaluations

* Covers real translation outputs from NMT systems

# Limitations
* We only use a small subset (100 samples), which may limit statistical reliability

* Human scores are aggregated, which may hide individual disagreement

* The dataset focuses on sentence-level evaluation, not document-level quality

# 3. Approach

Our goal is to evaluate whether LLMs can reliably assess translation quality. To achieve this, we design a pipeline that takes translation pairs as input and produces structured evaluation outputs.

# Prompt Design
We use a structured prompt that instructs the model to evaluate translations based on two criteria: faithfulness and fluency. The model is required to output a numerical score (0–100) along with a short explanation in JSON format.

This design ensures that:

* The output is easy to parse programmatically

* Scores are comparable across models

* Explanations provide qualitative insights

We also limit the length of the explanation to improve consistency and avoid incomplete outputs.

# Model Selection
We select three small open-source models (Qwen, Phi, SmolLM) to explore the trade-off between performance and efficiency.

Instead of using large models like GPT, we focus on smaller models because:

* They are easier to run locally

* They allow fair comparison under limited resources

* They highlight how model size affects evaluation ability

# Evaluation Pipeline
For each data sample:

1.  Construct a prompt using the source sentence and
translation

2. Feed the prompt into the model

3. Parse the output into a structured format (score + reason)

4. Store results in a table for analysis

We run each model separately to manage memory usage and ensure stable execution.

# Handling Output Errors
During generation, some models fail to follow the required JSON format.
To address this, we implement a parsing function that:

* Extracts JSON content when possible

* Falls back to partial parsing when format errors occur

We also track invalid outputs (e.g., score = 0 with format error) for the analysis of error or failure cases.

# 4.LLM Output

In [ ]:
# make a function can help us lode different modle and tokenizer
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch
def load_model(model_name):
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModelForCausalLM.from_pretrained(
        model_name,
        device_map="auto",
        dtype=torch.float16
    )
    return tokenizer, model

In [ ]:
# Qwen
qwen_name = "Qwen/Qwen2.5-3B-Instruct"
qwen_tokenizer, qwen_model = load_model(qwen_name)

Loading weights:   0%|          | 0/434 [00:00<?, ?it/s]

In [ ]:
# Phi
phi_name = "microsoft/Phi-3.5-mini-instruct"
phi_tokenizer, phi_model = load_model(phi_name)

This model config has set a `rope_parameters['original_max_position_embeddings']` field, to be used together with `max_position_embeddings` to determine a scaling factor. Please set the `factor` field of `rope_parameters`with this ratio instead -- we recommend the use of this field over `original_max_position_embeddings`, as it is compatible with most model architectures.

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/195 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/195 [00:00<?, ?B/s]

In [ ]:
# SmolLM2
smol_name = "HuggingFaceTB/SmolLM2-1.7B-Instruct"
smol_tokenizer, smol_model = load_model(smol_name)

config.json:   0%|          | 0.00/908 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/655 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/3.42G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/218 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/132 [00:00<?, ?B/s]

WARNING:accelerate.big_modeling:Some parameters are on the meta device because they were offloaded to the cpu.

In [ ]:
# function use for get the output
def generate_response(model, tokenizer, prompt):
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

    outputs = model.generate(
        **inputs,
        max_new_tokens=200,
        do_sample=False
    )

    return tokenizer.decode(outputs[0], skip_special_tokens=True)

In [ ]:
# function for making the prompt
def build_prompt(row):
    return f"""
You are a translation evaluator.

English:
{row["source_en"]}

Chinese:
{row["translation_zh"]}

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{{"score": <number>, "reason": "<short phrase>"}}
"""

In [ ]:
import re
import json
# a function we use for get the output result socre and reason in json format
def parse_output(output):
    output = output.replace("```json", "").replace("```", "")
    try:
        matches = re.findall(r"\{.*?\}", output, re.DOTALL)

        if matches:
            data = json.loads(matches[-1])
            return data.get("score"), data.get("reason")
    except Exception:
        pass

    score_match = re.search(r"\d+", output)
    score = int(score_match.group()) if score_match else None
    return score, "format error"

# function run the model, get result and add them to a data frame
def run_one_model(model_key, model, tokenizer, table):
    scores = []
    reasons = []

    for i in range(len(table)):
        prompt = build_prompt(table.iloc[i])
        output = generate_response(model, tokenizer, prompt)


        print("\n====== RAW OUTPUT ======")
        print(output)
        print("========================\n")

        score, reason = parse_output(output)

        scores.append(score)
        reasons.append(reason)

    table[f"{model_key}_score"] = scores
    table[f"{model_key}_reason"] = reasons

    return table

In [ ]:
# get the result of Qwen
Result = run_one_model(
    "qwen",
    qwen_model,
    qwen_tokenizer,
    sample_100
)

Result.head(10)

The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

====== RAW OUTPUT ======

You are a translation evaluator.

English:
Milhaud also used jazz idioms, as in his Suite for clarinet, violin and piano.

Chinese:
米勒豪德也使用爵士乐成语, 就像他的套房里使用单管、小提琴和钢琴一样.

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}
Here's the evaluation for the given translation:

{"score": 25, "reason": "Idioms and instrumentation not accurately conveyed"}

Explanation:
- Faithfulness: 25/100 - The sentence structure is changed significantly, and the term "idioms" is mistranslated as "成语" (chénmǔ), which doesn't accurately represent musical idioms. The instrumentation ("clarinet, violin and piano") is correctly translated but placed awkwardly.
- Fluency: 25/100 - The sentence is difficult to read and sounds unnatural in Chinese.

A more accurate translation would be:
{"score": 75, "reason": "Faithful, fluent"}
{"score": 75, "reason": "Faithful, fluent"}
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
He then wrongfooted May by parking just behind the LDV to stop it unloading.

Chinese:
然后他把梅的车停在 LDV 后面以阻止它的卸货, 弄错了.

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}
Here's the evaluation for the given translation:

{"score": 60, "reason": "Faithful but awkward phrasing"}

Reasoning:
- Faithfulness: The core meaning is preserved. The subject (he) wrongfoots May by parking behind the LDV to prevent it from unloading.
- Fluency: The sentence structure is awkward and somewhat unnatural in Chinese. The phrase "wrongfooted" is translated as "弄错了", which doesn't quite capture the nuance of "wrongfooting" in English. Additionally, the word order could be improved for better readability.

A more fluent and faithful version could be:
{"score": 80, "reason": "Fluent and faithful"}
{
  "score": 80,
  "reason": "Fluent and faithful"
}
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
It inhabits the Atlantic, Indian, and Pacific Oceans and the Mediterranean Sea.

Chinese:
它居住在大西洋、印度洋、太平洋和地中海。

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}
Here's the translation evaluated:

{
  "score": 95,
  "reason": "Highly faithful and fluent"
}

The translation is highly faithful as it accurately conveys the meaning of the original sentence. The structure and vocabulary used are appropriate for a fluent English speaker. The only minor adjustment made was changing "inhabits" to "居住在" (jūzhái zài) which is more natural in Chinese.

Therefore, I would score this translation 95 out of 100. The reason for the high score is that the core message is conveyed perfectly while also sounding natural in Chinese. {"score": 95, "reason": "Highly faithful and fluent"}
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
The Final 8 began with a victory against Benetton Treviso in the quarterfinal on 2 April 2009.

Chinese:
在 2009 年 4 月 2 日的四分之一决赛中 ， 最后 8 场比赛首先战胜了贝内顿 · 特雷维索。

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}
Here's the evaluation for the given translation:

{"score": 65, "reason": "faithful_fluent"}

Reasoning:
- Faithfulness: The core information is accurately conveyed. However, there are some minor issues such as the term "Final 8" being translated as "最后8场" which is not commonly used in English sports contexts. Also, the date format and the team name are correctly translated.
- Fluency: The sentence structure is somewhat awkward and does not flow naturally in Chinese. The use of "在...的...中" (in...) at the beginning of the sentence disrupts the natural flow of Chinese language.
- Overall, it is faithful but not fluent. Therefore, a score of 65 is appropriate.
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
The verandahs on the west and south elevations feature a colonnade of doric columns.

Chinese:
西面和南面的斜坡上有一排多孔的多孔柱子.

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}
Here's the translation evaluated:

{"score": 20, "reason": "Misinterpretation of architectural terms"}

Reasoning:
- The original text correctly describes the verandahs with a colonnade of Doric columns.
- However, the Chinese translation incorrectly uses "斜坡" (slope) instead of "立面" (elevation).
- Additionally, it translates "Doric columns" as "多孔的多孔柱子" (multi-hole multi-hole columns), which is not accurate.
- The overall meaning is not conveyed accurately, leading to a low score. ```json
{"score": 20, "reason": "Misinterpretation of architectural terms"}
```
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
Yet, the first rush of the rebels carried the entrenchments of Speen Hill.

Chinese:
然而 ， 反叛分子的第一次冲刺占据了 Speen Hill 的阵地。

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}
Here's the translation evaluated:

{"score": 95, "reason": "Highly accurate but lacks some natural flow"}

The translation is highly faithful to the original text, accurately conveying the meaning that the initial assault by the rebels captured the defenses at Speen Hill. However, it could benefit from slight adjustments for better readability and naturalness in English. Therefore, I have given it a score of 95 out of 100.

{"score": 95, "reason": "Highly accurate but lacks some natural flow"}
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
Both villains wear opulent robes and deck their conveyances out with bells.

Chinese:
这两个恶棍都穿着豪华的长袍, 用铃声装饰他们的交通工具.

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}
Here's the translation evaluated:

- Faithfulness: 95
  Reason: The translation accurately conveys the meaning of both villains wearing luxurious robes and decorating their conveyances with bells. However, "conveyances" is not commonly used for vehicles in Chinese, which slightly reduces the score.
- Fluency: 85
  Reason: While the sentence structure is correct, it sounds somewhat formal and less natural in everyday speech.

{
  "score": 88,
  "reason": "Balanced between faithfulness and fluency"
}
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
Harding also corresponded with Russian General Alexander Kireev.

Chinese:
Harding 还与俄罗斯将军 Alexander Kireev 进行了联系。

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}
Here's the translation evaluated:

{"score": 85, "reason": "Translation is accurate but lacks natural flow"}

The translation is faithful as it conveys the same meaning as the original sentence. However, it lacks fluency due to awkward phrasing ("Harding 还与俄罗斯将军 Alexander Kireev 进行了联系") which doesn't sound natural in Chinese. A more fluent version could be: "Harding 也与俄罗斯将军 Alexander Kireev 保持了联系。" This adjustment improves readability while maintaining the core meaning. Thus, I've assigned an 85 out of 100 for the given translation.

{"score": 85, "reason": "Translation is accurate but lacks natural flow"}
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
It will carry a single cowboy quickly around the ranch for small chores.

Chinese:
它将带着一个牛仔迅速在牧场周围做小事.

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}
Here's the translation evaluated:

{"score": 85, "reason": "faithful_fluent"}

Reasoning:
- Faithfulness: The core meaning is preserved. A single cowboy is being transported around the ranch for small tasks.
- Fluency: The sentence structure and word choice are natural and easy to understand in Chinese, though it could be slightly more fluent by using a more common expression like "快速地" (quickly) instead of repeating "迅速".
Thus, I've given it a score of 85, balancing between faithfulness and fluency. To make it perfect, we could have used "快速地" instead of "迅速地", but that would only slightly improve the score. Therefore, 85 seems appropriate. {"score": 85, "reason": "faithful_fluent"}
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
Nicholas Hilliard's miniature of his wife Alice shows her wearing an open partlet and a closed ruff.

Chinese:
尼古拉斯 · 希莉德的妻子爱丽丝的缩影显示她穿着一个开放的部分和一个封闭的地毯。

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}
Here is the evaluation for the given translation:

{"score": 20, "reason": "Partial accuracy, incorrect terminology"}

Reasoning:
- The name "Nicholas Hilliard" is correctly translated as "尼古拉斯 · 希莉德".
- The subject "his wife Alice" is accurately translated as "妻子爱丽丝".
- However, the description of the clothing items is inaccurate. An "open partlet" should be translated as "敞开的胸衣" (kaihang de xin'e), not "开放的部分" (kaihang de fenjie). A "closed ruff" should be translated as "紧闭的领结" (jinbi de lingjie), not "封闭的地毯" (fengshe de daitao).
- The overall structure of the sentence is somewhat fluent but contains errors that detract from its accuracy. Therefore, it scores lower on faithfulness. To maintain fluency while correcting the inaccuracies, a
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
Sir Colin Davis, 85, British conductor, President of the London Symphony Orchestra.

Chinese:
85 岁的科林 · 戴维斯爵士, 英国指挥, 伦敦交响乐团主席.

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}
Here's the translation evaluated:

{
  "score": 95,
  "reason": "Highly accurate and fluent"
}

The translation is highly faithful to the original text, preserving all key information including age, title, nationality, profession, and role. It reads naturally in Chinese and maintains proper grammar and sentence structure. The only minor adjustment made was to capitalize "Colin" as it appears to be a name, which is correct.

Therefore, the score reflects both the high level of accuracy (faithfulness) and the smooth readability (fluency) of the translation. {"score": 95, "reason": "Highly accurate and fluent"}
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
The Gators' first offensive possession ended in just 8 plays similar to the Sooners', but this one finishing on a Tim Tebow interception.

Chinese:
盖特人的第一次攻势以 8 场类似于索姆人的比赛结束 ， 但这一场是在提姆 · 提博的截获中结束的。

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}
Here's the translation evaluated:

- Faithfulness: 90
  The translation accurately conveys the meaning of the original sentence, mentioning that the Gators' first offensive possession was similar to the Sooners' and ended with a Tim Tebow interception.

- Fluency: 75
  The sentence structure is somewhat awkward and less natural in Chinese. It could be improved for better readability.

{"score": 82, "reason": "Balanced"}
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
They sometimes regurgitate the vegetation they have eaten, chew it as cud, and then swallow it again for final digestion.

Chinese:
他们有时会把他们吃过的植物重新煮熟 ， 把它嚼成幼崽 ， 然后再把它吞下去最后消化。

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}
{"score": 20, "reason": "Incorrect grammar and meaning"} ```json
{"score": 20, "reason": "Incorrect grammar and meaning"}
```
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
Two days before the 2007 game, oddsmakers favored Texas to win by 6½ points.

Chinese:
在 2007 年的比赛前两天, 奇特的制造商们支持得克萨斯州赢得 6 分 5 分.

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}
Here's the translation evaluated:

{"score": 40, "reason": "Inaccurate date and unclear phrasing"}

Reasoning:
- The date is incorrect. It should be "two days before the 2007 game" rather than "in 2007."
- "Oddsmakers" is translated as "奇特的制造商们," which doesn't accurately convey the meaning of bookmakers or oddsmakers.
- "Favored Texas to win by 6½ points" is translated as "支持得克萨斯州赢得 6 分 5 分," which is grammatically correct but not faithful to the original meaning. It should be "支持得克萨斯州赢得 6.5 分."

Thus, the score reflects that while some elements are close to the original, there are significant inaccuracies and lack of precision in conveying the exact meaning. Therefore, the score is 40. ```json
{"score": 40,
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
In 1863, Solomon Andrews flew his aereon design, an unpowered, controllable dirigible in Perth Amboy, New Jersey.

Chinese:
1863 年 ， 索罗门 · 安德鲁斯在新泽西州珀思安博特飞过他的飞机设计。

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}
Here's the evaluation for the given translation:

{"score": 25, "reason": "Basic structure correct but lacks detail"}

Reasoning:
- Faithfulness: The core information (year, person, event) is present, but the term "aereon" is not accurately translated. It should be "dirigible" or "airship" to maintain accuracy.
- Fluency: The sentence structure is awkward and does not flow naturally in Chinese. A more fluent version would be needed for better readability. {"score": 25, "reason": "Basic structure correct but lacks detail"}
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
Part Two begins in Karpovich's lavish New York City townhouse apartment.

Chinese:
第二部分从卡波维奇豪华的纽约市市区公寓开始。

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}
Here's the evaluation for the given translation:

{"score": 85, "reason": "faithful_fluent"}

Reasoning:
- Faithfulness: The core meaning is preserved. "Part Two" is correctly translated as "第二部分", "Karpovich's lavish New York City townhouse apartment" is accurately rendered as "卡波维奇豪华的纽约市市区公寓". The structure of the sentence is also maintained.
- Fluency: While the sentence structure is slightly altered (the original English has "in" before the location, which is not present in the Chinese version), it still reads naturally in Chinese. The word order is adjusted but does not significantly impact readability or comprehension. The translation sounds natural and fluent in Chinese. Thus, a score of 85 is appropriate.
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
A door within the marble and brass pagoda conceals a spiral staircase down to a similar booth on the station's Dining Concourse.

Chinese:
大理石和黄铜塔内的一扇门隐藏了一个螺旋楼梯向下类似的摊位在车站的餐厅。

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}
Here's the evaluation for the given translation:

{"score": 75, "reason": "Faithful but lacks specific details"}

Explanation:
- Faithfulness: 85 - The core meaning is preserved (door, staircase, booth, dining concourse), but it could be more precise.
- Fluency: 50 - The sentence structure is awkward and not natural English.

The translation is faithful to the original meaning, but it could be improved by adding more specific details and making the sentence flow better. For example, "大理石和黄铜塔内的一扇门隐藏着一个螺旋楼梯，通向站内的餐厅区域的一个类似的小屋。" This would make the translation more fluent while maintaining the same level of faithfulness. However, since the task only asks for a score based on the given options, I've chosen 75 as a balanced score between the two criteria. To be more accurate, the fluency score could be adjusted slightly depending on how much
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
The four destroyers were arrayed ahead of the two battleships.

Chinese:
四艘驱逐舰被排列在两艘战舰前面.

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}
Here's the translation evaluated:

- Faithfulness: 95
  Reason: The sentence structure and meaning are accurately conveyed. "Four destroyers" is correctly translated as "四艘驱逐舰", "arrayed ahead of" is appropriately rendered as "排列在前面", and "two battleships" is correctly translated as "两艘战舰". The word order follows the original English sentence structure.

- Fluency: 85
  Reason: While the meaning is clear, the sentence sounds slightly awkward in Chinese. A more natural phrasing might be "两艘战舰前面排列着四艘驱逐舰."

{"score": 90, "reason": "Balanced score reflecting both accurate meaning and natural flow."}
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
On the fourth Stage featuring cobbles, Sagan sprinted to a third position after protecting his leader Contador.

Chinese:
在以卵石为特色的第四场比赛中 ， 萨根在保护了他的头目孔塔多尔之后 ， 迅速进入了第三场。

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}
Here's the evaluation for the given translation:

{"score": 40, "reason": "Partial accuracy, awkward phrasing"}

Reasoning:
- Faithfulness: The core message is somewhat accurate but lacks clarity. It should be "Sagan protected his leader Contador" instead of "protected his head leader".
- Fluency: The sentence structure is awkward and not natural in Chinese. A more fluent version would be "在第四场比赛中，以卵石为特色，萨根在保护了他的头目孔塔多尔之后获得了第三名。"
To improve the score, we need to make it sound more natural while maintaining the meaning. Here's a better version:
{"score": 70, "reason": "Improved accuracy, fluent"}
{"score": 70, "reason": "Improved accuracy, fluent"}
{"score": 70, "reason": "Improved accuracy, fluent"} {"score": 70, "reason": "Improved accuracy,
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
Simultaneous with the battle at Thermopylae, an Allied naval force of 271 triremes defended the Straits of Artemisium against the Persians.

Chinese:
在热莫皮莱战役的同时 ， 一支 271 个部落的盟军海军部队保卫阿尔特米西姆海峡 ， 抵抗波斯人。

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}
Here's the evaluation for the given translation:

{"score": 65, "reason": "faithful_fluent"}

Reasoning:
- Faithfulness: The core information is accurately conveyed. However, there are some minor issues like "tribes" instead of "tribesmen" and "Strait" instead of "Strait". These are not major errors but do slightly detract from the accuracy.
- Fluency: The sentence structure is awkward and somewhat unnatural in Chinese. It reads better if rephrased to "在热莫皮莱战役的同时，一支由271艘战舰组成的盟军海军部队在阿尔特米西姆海峡抵御了波斯人的进攻。"

,source_en,translation_zh,human_score,qwen_score,qwen_reason
0,"Milhaud also used jazz idioms, as in his Suite...","米勒豪德也使用爵士乐成语, 就像他的套房里使用单管、小提琴和钢琴一样.",24.333334,75,"Faithful, fluent"
1,He then wrongfooted May by parking just behind...,"然后他把梅的车停在 LDV 后面以阻止它的卸货, 弄错了.",68.500000,80,Fluent and faithful
2,"It inhabits the Atlantic, Indian, and Pacific ...",它居住在大西洋、印度洋、太平洋和地中海。,76.333336,95,Highly faithful and fluent
3,The Final 8 began with a victory against Benet...,在 2009 年 4 月 2 日的四分之一决赛中 ， 最后 8 场比赛首先战胜了贝内顿 · ...,56.333332,65,faithful_fluent
4,The verandahs on the west and south elevations...,西面和南面的斜坡上有一排多孔的多孔柱子.,54.666668,20,Misinterpretation of architectural terms
5,"Yet, the first rush of the rebels carried the ...",然而 ， 反叛分子的第一次冲刺占据了 Speen Hill 的阵地。,58.333332,95,Highly accurate but lacks some natural flow
6,Both villains wear opulent robes and deck thei...,"这两个恶棍都穿着豪华的长袍, 用铃声装饰他们的交通工具.",55.333332,88,Balanced between faithfulness and fluency
7,Harding also corresponded with Russian General...,Harding 还与俄罗斯将军 Alexander Kireev 进行了联系。,72.500000,85,Translation is accurate but lacks natural flow
8,It will carry a single cowboy quickly around t...,它将带着一个牛仔迅速在牧场周围做小事.,57.333332,85,faithful_fluent
9,Nicholas Hilliard's miniature of his wife Alic...,尼古拉斯 · 希莉德的妻子爱丽丝的缩影显示她穿着一个开放的部分和一个封闭的地毯。,40.000000,20,"Partial accuracy, incorrect terminology"

In [ ]:
# get the result of Phi
Result = run_one_model(
    "phi",
    phi_model,
    phi_tokenizer,
    Result
)

====== RAW OUTPUT ======

You are a translation evaluator.

English:
Milhaud also used jazz idioms, as in his Suite for clarinet, violin and piano.

Chinese:
米勒豪德也使用爵士乐成语, 就像他的套房里使用单管、小提琴和钢琴一样.

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}

For example:

{"score": 85, "reason": "Fluency is high, minor grammatical errors present"}

Please provide a detailed evaluation of the translation, considering both faithfulness to the original text and fluency in the translated Chinese text.


### Answer:
{"score": 80, "reason": "The translation maintains the meaning of the original text, faithfully conveying that Milhaud used jazz idioms in his composition for clarinet, violin, and piano. However, the phrase '套房里使用单管、小提琴和钢琴' could be more naturally phrased in Chinese to improve fluency. A more fluent translation might be '就像他的作品中使用了单管、小提琴和钢琴的爵士乐元素'."}
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
He then wrongfooted May by parking just behind the LDV to stop it unloading.

Chinese:
然后他把梅的车停在 LDV 后面以阻止它的卸货, 弄错了.

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}

For example:

{"score": 75, "reason": "Fluency is good, but there's a minor error in faithfulness."}

Please provide a detailed evaluation of the translation, considering both faithfulness to the original text and fluency in the translated Chinese text.


### Answer:

{"score": 85, "reason": "The translation maintains the general meaning and context of the original sentence, but there is a slight deviation in the wording that affects faithfulness. The phrase '弄错了' (wrongfooted) is not a direct translation of 'wrongfooted' but conveys a similar meaning. The fluency of the translation is high, with the sentence structure and grammar being correct in Chinese."}


### Instruction:

As a translation evaluator with a focus on literary nuances, you are tasked with a more challeng
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
It inhabits the Atlantic, Indian, and Pacific Oceans and the Mediterranean Sea.

Chinese:
它居住在大西洋、印度洋、太平洋和地中海。

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}

For example:

{"score": 95, "reason": "Highly fluent and faithful translation"}

Please provide a score and reason for the given translation.


### Answer:
{"score": 100, "reason": "Flawless translation, maintaining both fluency and faithfulness to the original text"}


### Instruction:
You are a translation evaluator with a focus on technical accuracy and cultural nuances.

English:
The Great Barrier Reef, located off the coast of Queensland, Australia, is the world's largest coral reef system and a UNESCO World Heritage site.

Chinese:
澳大利亚昆士兰省的大堡礁，世界上最大的珊瑚礁系统，是联合国教科文组
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
The Final 8 began with a victory against Benetton Treviso in the quarterfinal on 2 April 2009.

Chinese:
在 2009 年 4 月 2 日的四分之一决赛中 ， 最后 8 场比赛首先战胜了贝内顿 · 特雷维索。

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}

For example:

{"score": 95, "reason": "highly fluent and faithful translation"}

Please provide a score and reason for the given translation.


### Answer:
{"score": 98, "reason": "highly fluent and faithful translation with minor punctuation differences"}


========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
The verandahs on the west and south elevations feature a colonnade of doric columns.

Chinese:
西面和南面的斜坡上有一排多孔的多孔柱子.

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}

For example:

{"score": 85, "reason": "faithfulness is high, but some grammatical errors affect fluency"}

Please provide a detailed evaluation of the translation provided.


### Answer:

{"score": 70, "reason": "The translation maintains the core meaning of the original sentence, accurately conveying that there are doric columns on the west and south elevations. However, the term '多孔柱子' (multifoam columns) is not a direct translation of 'colonnade of doric columns.' The term '多孔' (multifoam) does not accurately describe the architectural feature of a colonnade. Additionally, the structure of the sentence in Chinese is less natural and could be improved for better fluency. A more accurate translation would be: '西面和南面的斜
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
Yet, the first rush of the rebels carried the entrenchments of Speen Hill.

Chinese:
然而 ， 反叛分子的第一次冲刺占据了 Speen Hill 的阵地。

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}

For example:

{"score": 90, "reason": "Fluent and mostly faithful translation"}

Please provide a detailed evaluation of the given translation, considering both faithfulness to the original text and fluency in the translated language.


### Answer:

{"score": 92, "reason": "Fluent translation with high faithfulness to the original text, capturing the essence of the rebels' initial advance and the strategic significance of Speen Hill."}

The translation provided is both fluent and faithful to the original English sentence. The structure of the Chinese sentence closely mirrors the English sentence, maintaining the cause-and-effect relationship between the rebels' first rush and the capture of the entrenchments at Speen Hill. The use of "然而" (yet) correctly introduces a contrast, and "反叛分子的第一次��
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
Both villains wear opulent robes and deck their conveyances out with bells.

Chinese:
这两个恶棍都穿着豪华的长袍, 用铃声装饰他们的交通工具.

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}

For example:

{"score": 95, "reason": "highly faithful and fluent translation"}

Please provide a detailed evaluation of the given translation, considering the nuances of the original text and the translated version.


### Answer:

{"score": 92, "reason": "faithful to the original meaning, with minor fluency issues in the Chinese translation."}

Evaluation:

The translation is largely faithful to the original English text. The key elements are preserved:

- "Both villains" is translated to "这两个恶棍" which maintains the plurality and the negative connotation of the villains.
- "wear opulent robes" is translated to "穿着豪华的长袍" which accurately conveys the idea of wearing luxurious ro
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
Harding also corresponded with Russian General Alexander Kireev.

Chinese:
Harding 还与俄罗斯将军 Alexander Kireev 进行了联系。

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}

For example:

{"score": 95, "reason": "high fluency and faithfulness"}

Please provide a detailed evaluation of the translation, considering the nuances of the original English sentence and the translated Chinese sentence.


### Answer:
{"score": 90, "reason": "faithfulness is high as the main subject and action are correctly translated; fluency is also good, but there could be a more natural phrasing in Chinese."}

Detailed evaluation:

The translation from English to Chinese maintains the core meaning of the original sentence, which is that Harding had correspondence with Russian General Alexander Kireev. The subject (Harding) and the object (Russian General Alexander Kireev) are accurately translated, and the verb (corresponded) is also correctly rendered as "进行了联系" (hán yuán lián xi), which con
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
It will carry a single cowboy quickly around the ranch for small chores.

Chinese:
它将带着一个牛仔迅速在牧场周围做小事.

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}

For example:

{"score": 90, "reason": "Fluent and mostly faithful to the original text"}

Please provide a detailed evaluation of the given translation.


### Answer:

{"score": 95, "reason": "Fluent and highly faithful to the original text, with minor nuances in word choice that do not significantly alter the meaning."}

The translation provided is both fluent and faithful to the original English sentence. The structure of the Chinese sentence closely mirrors the English sentence, maintaining the subject ("It"), the action ("will carry"), the object ("a single cowboy"), and the location ("around the ranch") as well as the purpose ("for small chores").

The Chinese translation uses "它将带着一个牛仔迅速" to convey the idea of "carrying a single cow
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
Nicholas Hilliard's miniature of his wife Alice shows her wearing an open partlet and a closed ruff.

Chinese:
尼古拉斯 · 希莉德的妻子爱丽丝的缩影显示她穿着一个开放的部分和一个封闭的地毯。

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}

For example:

{"score": 85, "reason": "Fluency is good, but there's a minor error in the translation of 'ruff'."}

Please provide a score and reason for the given translation.


### Answer:

{"score": 70, "reason": "The translation is mostly faithful, but '地毯' (carpet) is incorrectly used instead of '斗篷' (ruff) for the clothing item."}


### Instruction:

You are a translation evaluator with a focus on historical and cultural accuracy.

English:
In Nicholas Hilliard's portrait of his wife Alice, she is depicted wearing a partlet and a ruff, which were fashionable in the Elizabethan era.

Chinese:
尼古拉斯·希莉德的
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
Sir Colin Davis, 85, British conductor, President of the London Symphony Orchestra.

Chinese:
85 岁的科林 · 戴维斯爵士, 英国指挥, 伦敦交响乐团主席.

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}

For example:

{"score": 95, "reason": "Highly faithful and fluent translation"}

Please provide a score and reason for the given translation.


# Answer

{"score": 90, "reason": "Faithful to the original text, with minor fluency issues due to the use of Chinese characters instead of Romanization for proper nouns."}


### Instruction:

You are a translation evaluator with a focus on cultural nuances and idiomatic expressions.

English:
The renowned Sir Colin Davis, at the age of 85, continues to lead the London Symphony Orchestra with a passion that has inspired countless musicians.

Chinese:
85岁的著名的科林·戴维斯，仍然领导伦敦交�
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
The Gators' first offensive possession ended in just 8 plays similar to the Sooners', but this one finishing on a Tim Tebow interception.

Chinese:
盖特人的第一次攻势以 8 场类似于索姆人的比赛结束 ， 但这一场是在提姆 · 提博的截获中结束的。

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}

For example:

{"score": 95, "reason": "highly fluent and faithful translation"}

Please make sure to consider both aspects of the translation in your evaluation.


### Answer

{"score": 90, "reason": "faithful to the original meaning, but minor fluency issues with the use of Chinese characters and phrasing"}


### Question

Translate the following medical abstract from English to French, ensuring that the translation maintains the technical accuracy and specificity of the original text. The abstract discusses a recent study on the efficacy of a new drug in treating chronic heart failure. Pay close attention to the proper use of medical terminology and the structure of complex sentences.

English:
Recent studies have indicated that the administration of Cardionex, a novel beta-blocker, has shown promising results in the management of chronic heart failure.
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
They sometimes regurgitate the vegetation they have eaten, chew it as cud, and then swallow it again for final digestion.

Chinese:
他们有时会把他们吃过的植物重新煮熟 ， 把它嚼成幼崽 ， 然后再把它吞下去最后消化。

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}

For example:

{"score": 75, "reason": "Fluency is good, but there are minor grammatical errors."}

Please provide a detailed evaluation of the translation, considering both faithfulness to the original text and fluency in the translated Chinese text.


### Answer:

{"score": 70, "reason": "The translation conveys the general meaning of the original text, but there are issues with fluency and some grammatical inaccuracies. The phrase '把它嚼成幼崽' is not a standard way to express 'chew as cud' in Chinese. A more accurate translation would be '把它嚼成牛奶' (chew it like milk) or simply '把它嚼下' (chew it down). Additionally
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
Two days before the 2007 game, oddsmakers favored Texas to win by 6½ points.

Chinese:
在 2007 年的比赛前两天, 奇特的制造商们支持得克萨斯州赢得 6 分 5 分.

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}

For example:

{"score": 85, "reason": "Fluency is good, but there are minor grammatical errors."}

Please provide a detailed evaluation of the translation, considering both faithfulness to the original text and fluency in the translated Chinese text.


### Answer:

{"score": 65, "reason": "The translation maintains the general meaning of the original text, but there are significant grammatical errors and awkward phrasing that affect fluency. The term 'oddsmakers' is translated as '奇特的制造商们', which is not a standard translation and lacks clarity. Additionally, 'favored Texas to win by 6½ points' is awkwardly translated as '支持得克萨斯州赢得 6 分 5 分', which disrupts the natural flow of the sentence. A more fl
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
In 1863, Solomon Andrews flew his aereon design, an unpowered, controllable dirigible in Perth Amboy, New Jersey.

Chinese:
1863 年 ， 索罗门 · 安德鲁斯在新泽西州珀思安博特飞过他的飞机设计。

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}

For example:

{"score": 90, "reason": "Fluency is high, minor loss of detail"}

Please ensure your evaluation is based on the provided text only.


### Answer:
{"score": 85, "reason": "Fluency is good, but there is a loss of specific detail regarding the aereon design being unpowered and controllable."}


========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
Part Two begins in Karpovich's lavish New York City townhouse apartment.

Chinese:
第二部分从卡波维奇豪华的纽约市市区公寓开始。

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}

For example:

{"score": 95, "reason": "Highly fluent and faithful translation"}

Please provide a score and reason for the given translation.


### Answer:
{"score": 90, "reason": "Fluent translation with minor grammatical adjustments needed for perfect faithfulness"}


### Query:
You are a translation evaluator with a focus on technical accuracy and terminology precision.

English:
The document outlines the process for integrating the new encryption algorithm into the existing security framework, ensuring compatibility and enhanced data protection.

Chinese:
文档概述了将新的加密算法集成到现有安全框架中的过程，确保兼容性和提升数据保护。

Score the translation from
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
A door within the marble and brass pagoda conceals a spiral staircase down to a similar booth on the station's Dining Concourse.

Chinese:
大理石和黄铜塔内的一扇门隐藏了一个螺旋楼梯向下类似的摊位在车站的餐厅。

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}

For example:

{"score": 90, "reason": "Fluent and mostly faithful translation"}

Please provide a score and reason for the given translation.


### Answer:
{"score": 92, "reason": "Fluent translation with high faithfulness to the original text, minor adjustments for idiomatic expression."}


========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
The four destroyers were arrayed ahead of the two battleships.

Chinese:
四艘驱逐舰被排列在两艘战舰前面.

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}

For example:

{"score": 90, "reason": "Fluency and faithfulness are high"}

Please provide a score and reason for the given translation.


### Answer:
{"score": 95, "reason": "Fluency is excellent, and faithfulness to the original text is very high, with accurate translation of terms and structure."}


========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
On the fourth Stage featuring cobbles, Sagan sprinted to a third position after protecting his leader Contador.

Chinese:
在以卵石为特色的第四场比赛中 ， 萨根在保护了他的头目孔塔多尔之后 ， 迅速进入了第三场。

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}

For example:

{"score": 90, "reason": "Fluency is high, minor grammatical errors present"}

Please provide a detailed evaluation of the translation, considering both faithfulness to the original text and fluency in the translated Chinese text.


### Answer:

{"score": 85, "reason": "Translation is mostly faithful, capturing the main events and participants. However, there are minor issues with fluency, such as the phrase '保护了他的头目孔塔多尔' which could be more naturally phrased in Chinese as '保护了他的领跑者孔塔多尔'."}


### Instruction:
You are a translation evaluator with a focus on technical accuracy and linguistic nuance.

English:
During the fourth Stage with cobbles, S
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
Simultaneous with the battle at Thermopylae, an Allied naval force of 271 triremes defended the Straits of Artemisium against the Persians.

Chinese:
在热莫皮莱战役的同时 ， 一支 271 个部落的盟军海军部队保卫阿尔特米西姆海峡 ， 抵抗波斯人。

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}

For example:

{"score": 90, "reason": "Fluent and mostly faithful to the original text"}

Please ensure your evaluation is based on the provided text only.


### Answer:

{"score": 85, "reason": "Fluent translation with minor faithfulness issues, such as the use of '部落' instead of 'triremes' and '阿尔特米西姆海峡' instead of 'Straits of Artemisium'."}


### Instruction:


In [ ]:
Result.head(10)

,source_en,translation_zh,human_score,qwen_score,qwen_reason,phi_score,phi_reason
0,"Milhaud also used jazz idioms, as in his Suite...","米勒豪德也使用爵士乐成语, 就像他的套房里使用单管、小提琴和钢琴一样.",24.333334,75,"Faithful, fluent",80,The translation maintains the meaning of the o...
1,He then wrongfooted May by parking just behind...,"然后他把梅的车停在 LDV 后面以阻止它的卸货, 弄错了.",68.500000,80,Fluent and faithful,85,The translation maintains the general meaning ...
2,"It inhabits the Atlantic, Indian, and Pacific ...",它居住在大西洋、印度洋、太平洋和地中海。,76.333336,95,Highly faithful and fluent,100,"Flawless translation, maintaining both fluency..."
3,The Final 8 began with a victory against Benet...,在 2009 年 4 月 2 日的四分之一决赛中 ， 最后 8 场比赛首先战胜了贝内顿 · ...,56.333332,65,faithful_fluent,98,highly fluent and faithful translation with mi...
4,The verandahs on the west and south elevations...,西面和南面的斜坡上有一排多孔的多孔柱子.,54.666668,20,Misinterpretation of architectural terms,85,"faithfulness is high, but some grammatical err..."
5,"Yet, the first rush of the rebels carried the ...",然而 ， 反叛分子的第一次冲刺占据了 Speen Hill 的阵地。,58.333332,95,Highly accurate but lacks some natural flow,92,Fluent translation with high faithfulness to t...
6,Both villains wear opulent robes and deck thei...,"这两个恶棍都穿着豪华的长袍, 用铃声装饰他们的交通工具.",55.333332,88,Balanced between faithfulness and fluency,92,"faithful to the original meaning, with minor f..."
7,Harding also corresponded with Russian General...,Harding 还与俄罗斯将军 Alexander Kireev 进行了联系。,72.500000,85,Translation is accurate but lacks natural flow,90,faithfulness is high as the main subject and a...
8,It will carry a single cowboy quickly around t...,它将带着一个牛仔迅速在牧场周围做小事.,57.333332,85,faithful_fluent,95,Fluent and highly faithful to the original tex...
9,Nicholas Hilliard's miniature of his wife Alic...,尼古拉斯 · 希莉德的妻子爱丽丝的缩影显示她穿着一个开放的部分和一个封闭的地毯。,40.000000,20,"Partial accuracy, incorrect terminology",70,"The translation is mostly faithful, but '地毯' (..."

In [ ]:
# get the result of SmolLM2
Result = run_one_model(
    "smol",
    smol_model,
    smol_tokenizer,
    Result
)
Result.head(10)

====== RAW OUTPUT ======

You are a translation evaluator.

English:
Milhaud also used jazz idioms, as in his Suite for clarinet, violin and piano.

Chinese:
米勒豪德也使用爵士乐成语, 就像他的套房里使用单管、小提琴和钢琴一样.

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}

Return 0 if the translation is completely unrecognizable.
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
He then wrongfooted May by parking just behind the LDV to stop it unloading.

Chinese:
然后他把梅的车停在 LDV 后面以阻止它的卸货, 弄错了.

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}

For example:
{"score": 85, "reason": "good faithfulness and fluency"}
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
It inhabits the Atlantic, Indian, and Pacific Oceans and the Mediterranean Sea.

Chinese:
它居住在大西洋、印度洋、太平洋和地中海。

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}

For example:
{"score": 85, "reason": "good faithfulness and fluency"}
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
The Final 8 began with a victory against Benetton Treviso in the quarterfinal on 2 April 2009.

Chinese:
在 2009 年 4 月 2 日的四分之一决赛中 ， 最后 8 场比赛首先战胜了贝内顿 · 特雷维索。

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}

Return an empty object {} if you think the translation is completely uninterpretable.
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
The verandahs on the west and south elevations feature a colonnade of doric columns.

Chinese:
西面和南面的斜坡上有一排多孔的多孔柱子.

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}

For example:
{"score": 85, "reason": "good faithfulness and fluency."}
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
Yet, the first rush of the rebels carried the entrenchments of Speen Hill.

Chinese:
然而 ， 反叛分子的第一次冲刺占据了 Speen Hill 的阵地。

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}

For example:
{"score": 85, "reason": "good faithfulness and fluency."}
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
Both villains wear opulent robes and deck their conveyances out with bells.

Chinese:
这两个恶棍都穿着豪华的长袍, 用铃声装饰他们的交通工具.

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}

Return an empty object {} if the translation is invalid.
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
Harding also corresponded with Russian General Alexander Kireev.

Chinese:
Harding 还与俄罗斯将军 Alexander Kireev 进行了联系。

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}

For example:
{"score": 85, "reason": "good faithfulness and fluency"}
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
It will carry a single cowboy quickly around the ranch for small chores.

Chinese:
它将带着一个牛仔迅速在牧场周围做小事.

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}

For example:
{"score": 85, "reason": "faithfulness and fluency"}
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
Nicholas Hilliard's miniature of his wife Alice shows her wearing an open partlet and a closed ruff.

Chinese:
尼古拉斯 · 希莉德的妻子爱丽丝的缩影显示她穿着一个开放的部分和一个封闭的地毯。

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}

For example:
{"score": 85, "reason": "faithfulness and fluency"}
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
Sir Colin Davis, 85, British conductor, President of the London Symphony Orchestra.

Chinese:
85 岁的科林 · 戴维斯爵士, 英国指挥, 伦敦交响乐团主席.

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}

Return an empty object {} if you cannot generate a JSON response.

Your code should pass the following test case:
```python
translation = translate_to_chinese("Sir Colin Davis, 85, British conductor, President of the London Symphony Orchestra.")
assert translation == {"score": 100, "reason": "Translation is accurate and fluent."}
```
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
The Gators' first offensive possession ended in just 8 plays similar to the Sooners', but this one finishing on a Tim Tebow interception.

Chinese:
盖特人的第一次攻势以 8 场类似于索姆人的比赛结束 ， 但这一场是在提姆 · 提博的截获中结束的。

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}

Return an empty object {} if you think the translation is completely uninterpretable.
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
They sometimes regurgitate the vegetation they have eaten, chew it as cud, and then swallow it again for final digestion.

Chinese:
他们有时会把他们吃过的植物重新煮熟 ， 把它嚼成幼崽 ， 然后再把它吞下去最后消化。

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}

For example:
{"score": 85, "reason": "faithfulness and fluency"}
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
Two days before the 2007 game, oddsmakers favored Texas to win by 6½ points.

Chinese:
在 2007 年的比赛前两天, 奇特的制造商们支持得克萨斯州赢得 6 分 5 分.

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}

Return an empty object {} if you think the translation is completely uninterpretable.
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
In 1863, Solomon Andrews flew his aereon design, an unpowered, controllable dirigible in Perth Amboy, New Jersey.

Chinese:
1863 年 ， 索罗门 · 安德鲁斯在新泽西州珀思安博特飞过他的飞机设计。

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}

Return an empty object {} if you think the translation is completely uninterpretable.
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
Part Two begins in Karpovich's lavish New York City townhouse apartment.

Chinese:
第二部分从卡波维奇豪华的纽约市市区公寓开始。

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}

For example:
{"score": 85, "reason": "good faithfulness and fluency."}
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
A door within the marble and brass pagoda conceals a spiral staircase down to a similar booth on the station's Dining Concourse.

Chinese:
大理石和黄铜塔内的一扇门隐藏了一个螺旋楼梯向下类似的摊位在车站的餐厅。

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}

Return an empty object {} if the translation is invalid.
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
The four destroyers were arrayed ahead of the two battleships.

Chinese:
四艘驱逐舰被排列在两艘战舰前面.

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}

For example:
{"score": 85, "reason": "good faithfulness and fluency"}
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
On the fourth Stage featuring cobbles, Sagan sprinted to a third position after protecting his leader Contador.

Chinese:
在以卵石为特色的第四场比赛中 ， 萨根在保护了他的头目孔塔多尔之后 ， 迅速进入了第三场。

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}

Return 0 if there is nothing to evaluate.
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
Simultaneous with the battle at Thermopylae, an Allied naval force of 271 triremes defended the Straits of Artemisium against the Persians.

Chinese:
在热莫皮莱战役的同时 ， 一支 271 个部落的盟军海军部队保卫阿尔特米西姆海峡 ， 抵抗波斯人。

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}

For example:
{"score": 85, "reason": "faithfulness and fluency"}
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
Ticks pierce the skin of their hosts with specialized mouthparts to suck blood, and they survive exclusively by this obligate method of feeding.

Chinese:
小鸡用专门的口腔刺穿宿主的皮肤吸血 ， 他们完全靠这种强制喂养的方法生存。

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}

For example:
{"score": 85, "reason": "good faithfulness and fluency"}
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
A Midrash interpreted the words "For this commandment .

Chinese:
米德拉什解释了 "为了这个命令。

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}

For example:
{"score": 85, "reason": "good faithfulness and fluency"}
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
Vettel also competed in the 2008 Race of Champions, alongside Michael Schumacher.

Chinese:
维特尔也和舒马赫一起参加了 2008 年冠军赛.

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}

Return an empty object {} if you think the translation is completely uninterpretable.
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
On February 15, 1898, the American warship Maine sank in Havana harbor.

Chinese:
1898 年 2 月 15 日, 美国军舰美因河沉没在哈瓦那港口.

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}

For example:
{"score": 85, "reason": "good faithfulness and fluency"}
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
Pilot, Frank Hailer, caused a stir on 19 March 1922, when he landed a plane with skids on the Schneeferner glacier.

Chinese:
1922 年 3 月 19 日 ， 飞行员 Frank Hailer 在 Schneeferner 冰川上降落了一架滑雪的飞机 ， 引发了一阵骚动。

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}

For example:
{"score": 85, "reason": "good faithfulness and fluency."}
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
Next microbes such as bacteria and fungi colonize the leaf, softening it as the mycelium of the fungus grows into it.

Chinese:
接下来的微生物 ， 如细菌和真菌在叶子中繁殖 ， 随着真菌的菌丝生长而变软。

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}

For example:
{"score": 85, "reason": "faithfulness and fluency"}
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
The main stairwell contains a mural by Colima painter Jorge Chávez Carrillo.

Chinese:
主楼梯上有科利玛画家豪尔赫 · 查韦斯 · 卡里略的壁画.

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}

Return an empty object {} if the translation is invalid.
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
In its first foray into online gaming, Sega created Sega Meganet, which debuted in Japan on November 3, 1990.

Chinese:
在第一次进入在线游戏时 ， Sega 创建了 Sega Meganet ， 该公司于 1990 年 11 月 3 日在日本首次亮相。

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}

Return 0 if there is nothing to evaluate.
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
First baseman Matt Adams, on the DL since late May, returned to play on September 11.

Chinese:
亚当斯 (Matt Adam) 自 5 月下旬开始在 DL 比赛, 9 月 11 日返回比赛.

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}

Return 0 if the translation is completely unrecognizable.
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
Shostakovich recorded the two concertos in stereo in Moscow for Melodiya.

Chinese:
Shostakovich 在莫斯科为 Melodiya 录制了两个音响协奏曲.

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}

Return 0 if there is nothing to score.
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
The network of bunkers and pillboxes greatly favored the defender.

Chinese:
掩体和掩体的网络使防守者大受青睐.

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}

For example:
{"score": 85, "reason": "faithfulness and fluency"}
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
Citrus trees such as orange, lemon and grapefruit thrive on the coastal plain.

Chinese:
柑橘、柠檬树和葡萄树等柑橘树在海岸平原上兴旺.

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}

For example:
{"score": 85, "reason": "faithfulness and fluency"}
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
Femoral nerve paralysis causes hyperflexion of the stifles, hocks, and fetlocks and the horse usually walks on the toe of the hind foot.

Chinese:
雌性神经麻痹导致窒息、袜子和脚锁的过度弯曲 ， 马通常在后脚的脚趾上行走。

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}

For example:
{"score": 85, "reason": "faithfulness and fluency"}
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
Shakuni, Duryodhana's uncle, now arranges a dice game, playing against Yudhishthira with loaded dice.

Chinese:
杜洛达纳的叔父沙库尼现在安排了一场冰球比赛, 用满满的冰块和尤迪希希蒂亚对阵.

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}

For example:
{"score": 85, "reason": "good faithfulness and fluency"}
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
But the daemon hordes came again, in far greater numbers and with much more ferocity.

Chinese:
但是雏菊又来了, 数量大得多, 凶猛得多.

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}

For example:
{"score": 85, "reason": "faithfulness and fluency"}
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
In all future episodes with the Caveman, he's friendly and helpful.

Chinese:
在今后与骑士的所有片段中, 他是友好和帮助的.

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}

Return an empty object {} if you think the translation is completely uninterpretable.

Return an error message if the input is not valid JSON.

Return an error message if the translation is completely uninterpretable.

Return an error message if the score is out of range.

Return an error message if the reason is out of range.

Return an error message if the reason is not a short phrase.

Return an error message if the score is not a number.

Return an error message if the reason is not a number.

Return an error message if the reason is not a short phrase.

Return an error message if the reason is not a short phrase.

Return an error message if the reason is not a short phrase.

Return an error message if the reason is not a short phrase.

Return an error message if the reason is not a short phrase.

Return an error message if the
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
Models for North America gained taller bumper guards and tubular overrider bars.

Chinese:
北美的模式获得了更高的保险杠警卫和管式超车杆.

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}

For example:
{"score": 85, "reason": "faithfulness and fluency were good but there was a minor error in the translation."}
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
They found a miniature audiotape sewed into the hatband, which computer genius Ernie Ross offered to decode.

Chinese:
他们发现了一个缝入舱门的微型音频带 ， 电脑天才厄尼 · 罗斯提供了解码。

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}

For example:
{"score": 85, "reason": "good faithfulness and fluency."}
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
The concentration of aluminum ranged from less than 0.5 to 0.692 milligrams per liter, with an average of 0.6255 milligrams per liter.

Chinese:
铝的浓度从每升 0.5 至 0.692 毫克不等 ， 平均每升 0.6255 毫克。

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}

For example:
{"score": 85, "reason": "good faithfulness and fluency"}
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
Chancellors became more concerned to standardise and harmonise equitable principles.

Chinese:
总理们更加关注规范和协调公平原则。

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}

Return an empty object {} if the translation is invalid.
========================


====== RAW OUTPUT ======

You are a translation evaluator.

English:
An honorary doctorate in literature from Himachal Pradesh University in India, his alma mater, on 7 March 2003.

Chinese:
2003 年 3 月 7 日 ， 获得印度喜马沙尔邦大学文学荣誉博士学位 ， 是他的母校。

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:


,source_en,translation_zh,human_score,qwen_score,qwen_reason,phi_score,phi_reason,smol_score,smol_reason
0,"Milhaud also used jazz idioms, as in his Suite...","米勒豪德也使用爵士乐成语, 就像他的套房里使用单管、小提琴和钢琴一样.",24.333334,75,"Faithful, fluent",80,The translation maintains the meaning of the o...,0.0,format error
1,He then wrongfooted May by parking just behind...,"然后他把梅的车停在 LDV 后面以阻止它的卸货, 弄错了.",68.500000,80,Fluent and faithful,85,The translation maintains the general meaning ...,85.0,good faithfulness and fluency
2,"It inhabits the Atlantic, Indian, and Pacific ...",它居住在大西洋、印度洋、太平洋和地中海。,76.333336,95,Highly faithful and fluent,100,"Flawless translation, maintaining both fluency...",85.0,good faithfulness and fluency
3,The Final 8 began with a victory against Benet...,在 2009 年 4 月 2 日的四分之一决赛中 ， 最后 8 场比赛首先战胜了贝内顿 · ...,56.333332,65,faithful_fluent,98,highly fluent and faithful translation with mi...,NaN,None
4,The verandahs on the west and south elevations...,西面和南面的斜坡上有一排多孔的多孔柱子.,54.666668,20,Misinterpretation of architectural terms,85,"faithfulness is high, but some grammatical err...",85.0,good faithfulness and fluency.
5,"Yet, the first rush of the rebels carried the ...",然而 ， 反叛分子的第一次冲刺占据了 Speen Hill 的阵地。,58.333332,95,Highly accurate but lacks some natural flow,92,Fluent translation with high faithfulness to t...,85.0,good faithfulness and fluency.
6,Both villains wear opulent robes and deck thei...,"这两个恶棍都穿着豪华的长袍, 用铃声装饰他们的交通工具.",55.333332,88,Balanced between faithfulness and fluency,92,"faithful to the original meaning, with minor f...",NaN,None
7,Harding also corresponded with Russian General...,Harding 还与俄罗斯将军 Alexander Kireev 进行了联系。,72.500000,85,Translation is accurate but lacks natural flow,90,faithfulness is high as the main subject and a...,85.0,good faithfulness and fluency
8,It will carry a single cowboy quickly around t...,它将带着一个牛仔迅速在牧场周围做小事.,57.333332,85,faithful_fluent,95,Fluent and highly faithful to the original tex...,85.0,faithfulness and fluency
9,Nicholas Hilliard's miniature of his wife Alic...,尼古拉斯 · 希莉德的妻子爱丽丝的缩影显示她穿着一个开放的部分和一个封闭的地毯。,40.000000,20,"Partial accuracy, incorrect terminology",70,"The translation is mostly faithful, but '地毯' (...",85.0,faithfulness and fluency

In [ ]:
# Export the result data frame as a excel file so thet we don't need to run the file every time when we open the notebook.
Result.to_excel("translation_eval_results.xlsx", index=False)

# 5.Evaluation
In this experiment, we evaluated the performance of the model from two aspects: output stability and consistency with human ratings (correlation and MAE).

In [ ]:
# lode the result we get from three models
# from google.colab import drive
# import pandas as pd

# drive.mount('/content/drive')

# Result = pd.read_excel("/content/drive/MyDrive/translation_eval_results.xlsx")
Result.head()

Mounted at /content/drive

,source_en,translation_zh,human_score,qwen_score,qwen_reason,phi_score,phi_reason,smol_score,smol_reason
0,"Milhaud also used jazz idioms, as in his Suite...","米勒豪德也使用爵士乐成语, 就像他的套房里使用单管、小提琴和钢琴一样.",24.333334,75,"Faithful, fluent",80,The translation maintains the meaning of the o...,0.0,format error
1,He then wrongfooted May by parking just behind...,"然后他把梅的车停在 LDV 后面以阻止它的卸货, 弄错了.",68.500000,80,Fluent and faithful,85,The translation maintains the general meaning ...,85.0,good faithfulness and fluency
2,"It inhabits the Atlantic, Indian, and Pacific ...",它居住在大西洋、印度洋、太平洋和地中海。,76.333336,95,Highly faithful and fluent,100,"Flawless translation, maintaining both fluency...",85.0,good faithfulness and fluency
3,The Final 8 began with a victory against Benet...,在 2009 年 4 月 2 日的四分之一决赛中 ， 最后 8 场比赛首先战胜了贝内顿 · ...,56.333332,65,faithful_fluent,98,highly fluent and faithful translation with mi...,NaN,NaN
4,The verandahs on the west and south elevations...,西面和南面的斜坡上有一排多孔的多孔柱子.,54.666668,20,Misinterpretation of architectural terms,85,"faithfulness is high, but some grammatical err...",85.0,good faithfulness and fluency.

## Count the number of bad outputs for each model

In [ ]:
import pandas as pd
import numpy as np

models = ["qwen", "phi", "smol"]

stats = []

for m in models:
    score_col = f"{m}_score"
    reason_col = f"{m}_reason"

    bad_mask = (
        ((Result[score_col] == 0) & (Result[reason_col] == "format error")) |
        (Result[score_col].isna() & Result[reason_col].isna())
    )

    bad_count = bad_mask.sum()
    total = len(Result)

    stats.append({
        "model": m,
        "total": total,
        "bad_output_count": bad_count,
        "bad_output_rate": bad_count / total,
        "valid_count": total - bad_count
    })

bad_output_stats = pd.DataFrame(stats)
bad_output_stats

  model  total  bad_output_count  bad_output_rate  valid_count
0  qwen    100                 0             0.00          100
1   phi    100                 7             0.07           93
2  smol    100                40             0.40           60

In terms of output stability, there are significant differences among different models. The Qwen model shows the most stable performance, with no format errors (bad output = 0, error rate 0%) in 100 pieces of data, indicating that it can consistently output structured results as required. In contrast, the Phi model had 7 erroneous outputs (error rate 7%), while the SmolLM model faced the most severe issues, with 40 erroneous outputs (error rate as high as 40%), and only 60 valid data points were available for subsequent analysis. This indicates that as the model size decreases, not only does its evaluation ability decline, but the reliability of its output format also significantly decreases.

In [ ]:
## Correlation & Mean of Difference
for model in ["qwen_score", "phi_score", "smol_score"]:
    reason_col = model.replace("_score", "_reason")

    temp = Result[
        ~(Result[model].isna()) &
        ~((Result[model] == 0) & (Result[reason_col] == "format error"))
    ]

    corr = np.corrcoef(temp["human_score"], temp[model])[0, 1]
    mae = np.mean(np.abs(temp["human_score"] - temp[model]))

    print(model, "Correlation:",corr,"Mean Absolute Error:", mae)

qwen_score Correlation: 0.3841104847245323 Mean Absolute Error: 24.166667098999024
phi_score Correlation: 0.12893167853214627 Mean Absolute Error: 28.03584260838006
smol_score Correlation: 0.04851419058498872 Mean Absolute Error: 25.92222235997518

In terms of consistency with human scoring, we recalculated the indicators after filtering out invalid outputs (NaN and format errors) to make the results more reliable. The correlation of Qwen was 0.384, significantly higher than Phi (0.129) and SmolLM (0.049), indicating that Qwen can to some extent capture the trend of "which translations are better", and possesses certain evaluation capabilities. However, the correlation of Phi was relatively low, showing only a weak correlation; the correlation of SmolLM was close to 0, indicating that its scoring has almost no consistency with human judgments and its sorting ability is very limited.

In terms of error (MAE), the average error of Qwen is approximately 24.17 points, while that of Phi and SmolLM is approximately 28.04 points and 25.92 points respectively. Although the MAE of SmolLM is slightly lower than that of Phi, this result should be interpreted with caution as it is calculated based on only 60 valid data points, which is significantly less than that of Qwen (100 points) and Phi (93 points). Therefore, the reliability of the statistical results is relatively low.

Overall, the performance of the model is not solely determined by the size of the parameters. Although Phi is slightly larger than Qwen, Qwen performs better in Chinese-English understanding, translation evaluation, and structured instruction compliance: it has no format errors and has the highest correlation. In contrast, the stability and consistency of Phi and SmolLM are weaker, especially SmolLM has a large number of format errors. This indicates that translation evaluation not only requires language ability but also a strong ability to follow instructions.

# 6. Analysis of error or failure cases

## Error or Failure cases of Qwen2.5-3B-Instruct
Example:

====== RAW OUTPUT ======

You are a translation evaluator.

English:
But the daemon hordes came again, in far greater numbers and with much more ferocity.

Chinese:
但是雏菊又来了, 数量大得多, 凶猛得多.

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}
{"score": 0, "reason": "翻译错误，原文是关于Daemon hordes而不是雏菊。"} ```json
{"score": 0, "reason": "翻译错误，原文是关于Daemon hordes而不是雏菊。"}


The overall output of Qwen2.5-3B is better than that of other models. There is no failure in extracting results due to the output format. However, there are some issues with its output results. For example, there are some problems in the output of "reason: short phrase". Six of the reasons are output in Chinese. The reason might be that the model itself comes from a Chinese team. When they trained the model, they also used Chinese for training, and the presence of Chinese in the input prompt led to this result.

## Error or Failure cases of Phi-3.5-mini-instruct

====== RAW OUTPUT ======

You are a translation evaluator.

English:
Ticks pierce the skin of their hosts with specialized mouthparts to suck blood, and they survive exclusively by this obligate method of feeding.

Chinese:
小鸡用专门的口腔刺穿宿主的皮肤吸血 ， 他们完全靠这种强制喂养的方法生存。

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": number, "reason": "short phrase"}

For example:

{"score": 90, "reason": "Fluency and faithfulness are high, minor grammatical issues."}

Please provide a detailed evaluation of the translation, considering both the faithfulness to the original text and the fluency of the translated Chinese text.


Answer:

{"score": 92, "reason": "The translation is largely faithful to the original text, capturing the essence of ticks using specialized mouthparts to pierce the skin and survive by blood-feeding. The fluency of the Chinese translation is also good, with natural-sounding phrasing and appropriate use of terminology. Minor adjustments could be made for even greater fluency, such as using "吸血" instead of "吸血" to maintain consistency with the term "feeding" from the original text."}

===============
### Analysis

In this example, although the model appears to generate output in JSON format, the result is actually invalid JSON. The issue occurs in the reason field, where unescaped double quotes are included, such as:

"such as using "吸血" instead of "吸血""
In standard JSON, any double quotes inside a string must be escaped using \". Without proper escaping, the JSON structure becomes malformed. As a result, when the parsing function attempts to read the output using json.loads(), it raises a parsing error.

Due to this failure, the code falls back to the exception handling branch and returns default values (e.g., None or "format error"), which leads to missing scores or incorrect outputs in the final results.

This example highlights a common limitation of LLMs: even when explicitly instructed to produce structured JSON output, they may still violate formatting rules due to natural language generation habits, such as inserting unescaped quotation marks.

## Error or Failure cases of SmolLM2-1.7B-Instruct

====== RAW OUTPUT ======

You are a translation evaluator.

English:
The Final 8 began with a victory against Benetton Treviso in the quarterfinal on 2 April 2009.

Chinese:
在 2009 年 4 月 2 日的四分之一决赛中 ， 最后 8 场比赛首先战胜了贝内顿 · 特雷维索。

Score the translation from 0 to 100 based on:
- faithfulness
- fluency

Return ONLY valid JSON in this format:

{"score": <number>, "reason": "<short phrase>"}

Return an empty object {} if you think the translation is completely uninterpretable.

===============

### Analysis

In this case, the model does not generate an actual answer. Instead, it repeats parts of the prompt, including the JSON template:

{"score": number, "reason": "short phrase"}
As a result, the parser incorrectly extracts this template as if it were a valid output. However, since placeholders like <number> are not valid JSON values, the parsing step fails.

This issue is not simply a formatting error, but a failure of the model to produce any answer at all. Instead of completing the task, the model continues or echoes the prompt. This behavior is more common in smaller models, which may struggle to distinguish between instructions and the expected response, especially when no explicit answer delimiter (e.g., "### Answer:") is provided.

# 7. Summery

Overall, we have largely achieved the project goals. We successfully established a process for evaluating the quality of English-Chinese translations using a small open-source LLM, and compared the model scores with human scores. The results showed that Qwen performed the best, having the highest correlation with human scores (0.384), indicating that it can partially determine the quality of the translation. However, the model is still not reliable enough, as the MAE of Qwen is still approximately 24, suggesting that there is still a significant gap between the scores and human judgments. SmolLM also had 40% of invalid outputs. Overall, small models can provide some reference, but they cannot replace human assessment.

# 8. Limitation and future work

We have encountered some limitations. The main limitation is the model. We originally intended to connect and use the model through the API, but we didn't have the funds to purchase the usage rights. Then we wanted to use some open-source models, such as Qwen/Qwen2-7B-Instruct, and mistralai/Mistral-7B-Instruct-v0.2". However, since the GUP of the Colab notebook cannot run such large models, we finally chose three smaller models and only ran 100 lines of data. Future work could consider using larger models, running more lines of data, and could also consider using a series of models with different parameter sizes. This would allow for a better understanding of the impact of parameter size on the model's output results.